plugins {
    id 'java'
}

group = 'com.libentity'
version = '0.0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.palantir.javapoet:javapoet:0.7.0")
    implementation("org.apache.commons:commons-lang3:3.17.0")
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.google.testing.compile:compile-testing:0.21.0'
    testImplementation 'com.google.truth:truth:1.4.2'

}

test {
    useJUnitPlatform()
}