version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: spring_example_postgres
    environment:
      POSTGRES_USER: springuser
      POSTGRES_PASSWORD: springpass
      POSTGRES_DB: springexample
    ports:
      - "25432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
